export const galleryImages: string[] = [
    "/cat.png",
    "/cat.png",
    "/cat.png",
    "/cat.png",
    "/cat.png",
    "/cat.png",
    "/cat.png",
    "/cat.png",
    "/cat.png",
    "/cat.png",
    "/cat.png",
    "/cat.png",
    "/cat.png",
];